# Generated by Django 3.2.8 on 2022-01-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('thumbnail', models.ImageField(upload_to='media/thumbnails/')),
                ('audio', models.FileField(upload_to='media/audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
