# Generated by Django 3.2.8 on 2022-01-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('author', models.CharField(max_length=64, unique=True)),
                ('genre', models.CharField(choices=[('all', 'All'), ('pop', 'Pop'), ('instrumental', 'Instrumental'), ('rock', 'Rock'), ('rap', 'Rap'), ('metal', 'Metal'), ('jazz', 'Jazz')], default='All', max_length=32)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('audio', models.FileField(upload_to='audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/albums/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.song')),
            ],
        ),
    ]
