# Generated by Django 3.2.8 on 2022-01-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('All', 'all'), ('Pop', 'pop'), ('Instrumental', 'instrumental'), ('Rock', 'rock'), ('Rap', 'rap'), ('Metal', 'metal'), ('Jazz', 'jazz')], default='All', max_length=32),
        ),
    ]
