# Generated by Django 3.2.8 on 2022-01-08 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_recentsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsong',
            name='listened_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
