# Generated by Django 3.2.8 on 2022-01-19 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_auto_20220117_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.PositiveBigIntegerField()),
                ('rate_type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LikedSong',
        ),
    ]
