# Generated by Django 3.2.8 on 2022-01-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220119_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AlterField(
            model_name='song',
            name='dislikes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.song')),
            ],
        ),
    ]
