# Generated by Django 3.2.8 on 2022-01-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220113_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='producer_name',
            new_name='author',
        ),
    ]
