# Generated by Django 3.2.8 on 2022-01-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
