# Generated by Django 3.2.8 on 2022-01-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_album_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='thumbnail',
            new_name='profile',
        ),
    ]
