# Generated by Django 3.2.8 on 2022-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_thumbnail_album_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=16),
        ),
    ]
