# Generated by Django 3.2.8 on 2022-01-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedsong',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='recentsong',
            name='song_id',
        ),
        migrations.AddField(
            model_name='ratedsong',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentsong',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.song'),
            preserve_default=False,
        ),
    ]
