# Generated by Django 3.2.8 on 2022-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='band_name',
            field=models.CharField(max_length=72, null=True, unique=True),
        ),
    ]
