# Generated by Django 3.2.8 on 2022-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cuser_band_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='profile',
            field=models.ImageField(default='profiles/def.png', upload_to='profiles/'),
        ),
    ]
