# Generated by Django 3.2.8 on 2022-01-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cuser_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuser',
            old_name='band_name',
            new_name='producer_name',
        ),
    ]
